/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PrimeFactors;

import java.util.ArrayList;
import java.util.List;

public class PrimeFactors {

    public String getFactors(int number) {
        List<Integer> factorList = new ArrayList<>();

        if(number == 1) {
            return factorList.toString();
        }

        if(number % 2 == 0 && number > 2) {
            number /= 2;
            factorList.add(number);
        }

        factorList.add(number);
        return factorList.toString();
    }
}
