/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PrimeFactors;

import java.util.ArrayList;
import java.util.List;

public class PrimeFactors {

    public String getFactors(int number) {
        if(number == 1) {
            return "";
        }
        return "[" + number + "]";
    }
}
