/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PrimeFactors;

import org.junit.Test;
import static org.junit.Assert.*;

public class PrimeFactorsTest {
    @Test
    public void GivenOneFactorsAreIsEmpty() {
        PrimeFactors primeFactors = new PrimeFactors();
        assertEquals("", primeFactors.getFactors(1));
    }

    @Test
    public void GivenTwoFactorsAreTwo() {
        PrimeFactors primeFactors = new PrimeFactors();
        assertEquals("[2]", primeFactors.getFactors(2));
    }

    @Test
    public void GivenThreeFactorsAreThree() {
        PrimeFactors primeFactors = new PrimeFactors();
        assertEquals("[3]", primeFactors.getFactors(3));
    }
}
