/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PrimeFactors;

import org.junit.Test;
import static org.junit.Assert.*;

public class PrimeFactorsTest {
    @Test
    public void GivenOneFactorsAreIsEmpty() {
        PrimeFactors primeFactors = new PrimeFactors();
        assertEquals("[]", primeFactors.getFactors(1));
    }

    @Test
    public void GivenTwoFactorsAreTwo() {
        PrimeFactors primeFactors = new PrimeFactors();
        assertEquals("[2]", primeFactors.getFactors(2));
    }

    @Test
    public void GivenThreeFactorsAreThree() {
        PrimeFactors primeFactors = new PrimeFactors();
        assertEquals("[3]", primeFactors.getFactors(3));
    }

    @Test
    public void GivenFourFactorsAreTwoTwo() {
        PrimeFactors primeFactors = new PrimeFactors();
        assertEquals("[2, 2]", primeFactors.getFactors(4));
    }

    @Test
    public void GivenSixFactorsAreThreeTwo() {
        PrimeFactors primeFactors = new PrimeFactors();
        assertEquals("[3, 2]", primeFactors.getFactors(6));
    }

    @Test
    public void GivenEightFactorsAreTwoTwoTwo() {
        PrimeFactors primeFactors = new PrimeFactors();
        assertEquals("[2, 2, 2]", primeFactors.getFactors(8));
    }

    @Test
    public void GivenNineFactorsAreThreeThree() {
        PrimeFactors primeFactors = new PrimeFactors();
        assertEquals("[3, 3]", primeFactors.getFactors(9));
    }
}
